# Generated by Django 2.2.2 on 2019-09-29 03:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('authtoken', '0002_auto_20160226_1747'),
    ]

    operations = [
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=20)),
                ('nit', models.CharField(default='', max_length=20)),
                ('date_address', models.DateField(blank=True)),
                ('NoPrescripcion', models.CharField(default='', max_length=20)),
                ('TipoTec', models.CharField(default='', max_length=1)),
                ('ConTec', models.CharField(default='', max_length=2)),
                ('TipoIdPaciente', models.CharField(default='', max_length=2)),
                ('NoIdPaciente', models.CharField(default='', max_length=17)),
                ('NoEntrega', models.CharField(default='', max_length=2)),
                ('NoSubEntrega', models.CharField(default='', max_length=2)),
                ('TipoIDProv', models.CharField(default='', max_length=2)),
                ('NoIDProv', models.CharField(default='', max_length=17)),
                ('CodMunEnt', models.CharField(default='', max_length=5)),
                ('FecMaxEnt', models.CharField(default='', max_length=10)),
                ('CantTotAEntregar', models.CharField(default='', max_length=10)),
                ('DirPaciente', models.CharField(default='', max_length=80)),
                ('CodSerTecAEntregar', models.CharField(default='', max_length=20)),
                ('token', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='authtoken.Token')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
    ]
