# Generated by Django 2.2.2 on 2019-09-29 06:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('addressing', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='address',
            options={'ordering': ['date_address']},
        ),
        migrations.RemoveField(
            model_name='address',
            name='name',
        ),
        migrations.RemoveField(
            model_name='address',
            name='nit',
        ),
        migrations.RemoveField(
            model_name='address',
            name='token',
        ),
    ]
