# Generated by Django 2.2.2 on 2019-09-29 06:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0001_initial'),
        ('addressing', '0002_auto_20190929_0659'),
    ]

    operations = [
        migrations.AddField(
            model_name='address',
            name='company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='company.Company'),
        ),
    ]
