# Generated by Django 2.2.2 on 2019-09-29 07:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('addressing', '0003_address_company'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='address',
            options={'ordering': ['NoPrescripcion']},
        ),
    ]
