# Generated by Django 2.2.2 on 2019-10-09 04:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Program',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('IDProgramacion', models.CharField(default='', max_length=32)),
                ('NoPrescripcion', models.CharField(default='', max_length=20)),
                ('TipoTec', models.CharField(default='', max_length=1)),
                ('ConTec', models.CharField(default='', max_length=2)),
                ('TipoIDPaciente', models.CharField(default='', max_length=2)),
                ('NoIdPaciente', models.CharField(default='', max_length=17)),
                ('NoEntrega', models.CharField(default='', max_length=2)),
                ('FecMaxEnt', models.CharField(default='', max_length=10)),
                ('TipoIDSedeProv', models.CharField(default='', max_length=2)),
                ('NoIDSedeProv', models.CharField(default='', max_length=9)),
                ('CodSedeProv', models.CharField(default='', max_length=15)),
                ('CodSerTecAEntregar', models.CharField(default='', max_length=20)),
                ('CantTotAEntregar', models.CharField(default='', max_length=10)),
                ('FecProgramacion', models.CharField(default='', max_length=16)),
                ('EstProgramacion', models.CharField(default='', max_length=16)),
                ('FechaAnulacion', models.CharField(default='', max_length=16)),
            ],
            options={
                'ordering': ['NoPrescripcion'],
            },
        ),
    ]
