# Generated by Django 2.2.2 on 2019-10-11 02:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('programs', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='program',
            old_name='CodSerTecAEntregar',
            new_name='CodTecAEntregar',
        ),
    ]
