# Generated by Django 2.2.2 on 2019-10-11 04:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('programs', '0002_auto_20191011_0248'),
    ]

    operations = [
        migrations.AlterField(
            model_name='program',
            name='FecProgramacion',
            field=models.CharField(default='', max_length=10),
        ),
    ]
