# Generated by Django 2.2.2 on 2019-06-20 04:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=255)),
                ('code', models.CharField(default='', max_length=255)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Shop',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=255)),
                ('address', models.CharField(default='', max_length=255)),
                ('phone', models.CharField(default='', max_length=255)),
                ('site', models.CharField(default='', max_length=255)),
                ('email', models.EmailField(max_length=254)),
                ('country', models.CharField(default='', max_length=255)),
                ('district', models.CharField(default='', max_length=255)),
                ('city', models.CharField(default='', max_length=255)),
                ('description', models.TextField(max_length=2000)),
                ('category', models.ManyToManyField(to='shop.Category')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
    ]
